applications:
  - application:
    name: gfr
    tpjName: foretag
    probe: UgkForetagProbe
    monitors:
      - monitor:
        path: /service/foretag/3.0/debug/servicelog
      - monitor:
        path: /service/foretag/4.0/debug/servicelog
      - monitor:
        path: /service/foretag/5.0/debug/servicelog
      - monitor:
        path: /service/foretag/6.0/debug/servicelog

  - application:
    name: geo
    probe: UgkGeoProbe
    monitors:
      - monitor:
        path: /geo/debug/resourcelog

  - application:
    name: cpr
    probe: CprProbe

  - application:
    name: agselect
    probe: MarknadsanalysProbe

updateFrequenzy:
  jenkins:
    period: 30
    timeUnit: SECONDS

  monitor:
    period: 1
    timeUnit: MINUTES

  probe:
    period: 30
    timeUnit: SECONDS

continuousIntegration:
  host: l7700676.ws.ams.se
  port: 8080

tpjadmin:
  host: l7700759.wpa.ams.se
  port: 8180
  uri: /tpjadmin/rest/properties/v0/wildfly/instances/

